server:
  port: 9898
  ssl:

    key-store: classpath:

#    key-store-password: 
    key-store-password: 

    keyStoreType: JKS



spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  file:
    # 输出的log文件名
    name: 
    # 输出的文件的路径
    path: 
    # 限制日志文件的大小
    max-size: 10MB

  level:
    # 输出级别
    root: info
    # 特定的mapper下的输出级别
    com.example.demo.mapper: debug
  # xml配置文件
  config: classpath:logback-spring.xml

