server:
  port: 9898
  ssl:

    key-store: classpath:yujian.com.jks

#    key-store-password: v239qg6i
    key-store-password: hslk8fg7

    keyStoreType: JKS



spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(port=1521)(host=120.79.239.161))(connect_data=(service_name=pdborcl)))
    username: yjami
    password: yjami_2018
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  file:
    # 输出的log文件名
    name: YUJIANminiAppServiceLog
    # 输出的文件的路径
    path: C:\miniAppService
    # 限制日志文件的大小
    max-size: 10MB

  level:
    # 输出级别
    root: info
    # 特定的mapper下的输出级别
    com.example.demo.mapper: debug
  # xml配置文件
  config: classpath:logback-spring.xml

